name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install lua
      run: sudo apt-get install lua5.4 lua5.4-dev
    - uses: leafo/gh-actions-lua@v10.0.0
    - name: Download nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
    - name: Select nightly toolchain
      run: rustup default nightly
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Generate code coverage
      run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: codecov.json
        fail_ci_if_error: true
    #- name: Build
    #  run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
